require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'spec/shared/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'test-apps/**/*'

# -----------------------------------
# TODO: Enable and fix the cops below
# -----------------------------------

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Lint:
  Enabled: true

Metrics:
  Enabled: true

Naming:
  Enabled: true

Performance:
  Enabled: true

Rake:
  Enabled: true

RSpec:
  Enabled: true

Security:
  Exclude:
    - 'spec/**/*'

Style:
  Enabled: true

# --------------------------------------
# Cops below this line set intentionally
# --------------------------------------

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 20

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/ImplicitExpect:
  EnforcedStyle: is_expected

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/ParallelAssignment:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
