defaults: &defaults
  allow_read_secondary: true
  replica_set:
    - uri : 'http://johnny:seed@host.local/'
    - uri : 'http://johnny:seed@host.local:27018/'
test:
  <<: *defaults
  database: mongoid_config_test

