defaults: &defaults
  allow_read_secondary: true
  replica_set:
    - uri : 'http://johnny:seed@localhost/'
    - uri : 'http://johnny:seed@localhost:27018/'
test:
  <<: *defaults
  database: mongoid_config_test

